[dev]
functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["!node_modules/.prisma/client/libquery_engine-*"]
  directory = "netlify/functions"
  external_node_modules = ["openai"]
  timeout = 26
